version: '3.3'

services:
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - ./wp-content:/var/www/html/wp-content
     ports:
       - "8080:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:8081
       WORDPRESS_DB_USER: legendarylion
       WORDPRESS_DB_PASSWORD: legendary^2015!

   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: wordpress
       MYSQL_USER: admin
       MYSQL_PASSWORD: password
     ports:
       - "8081:3306"
volumes:
    wordpress_files:
    db_data:
